[package]
name = "kiss-daemon"
version = "1.2.5"
edition = "2021"
description = "KISS Security Daemon"
authors = ["Michael Hoyt"]

[[bin]]
name = "kiss-daemon"
path = "src/main.rs"

[dependencies]
# Shared dependencies
cfg-if = "1.0"
goldberg = "*"

# Target-specific dependencies
[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_StationsAndDesktops",
    "Win32_System_SystemInformation",
    "Win32_UI_Shell",
    "Win32_Graphics_Gdi",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.packager]
before-packaging-command = "cargo build --release"
product-name = "KissDaemon"
identifier = "com.kiss.daemon"
formats = ["deb", "nsis", "dmg"]

[[package.metadata.packager.binaries]]
path = "kiss-daemon"
main = true
